name: Linting

on: pull_request

jobs:
  prettier:
    name: Biome Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.1'

      - run: npm ci

      - run: npm run lint